"""Canonical Phish studio album song seed data."""

SONGS = [
    {"name": "Fee"},
    {"name": "You Enjoy Myself"},
    {"name": "Esther"},
    {"name": "Golgi Apparatus"},
    {"name": "Foam"},
    {"name": "Dinner and a Movie"},
    {"name": "Divided Sky"},
    {"name": "David Bowie"},
    {"name": "Fluffhead"},
    {"name": "Fluff's Travels"},
    {"name": "Contact"},
    {"name": "Union Federal"},
    {"name": "Sanity"},
    {"name": "Icculus"},
    {"name": "The Squirming Coil"},
    {"name": "Reba"},
    {"name": "My Sweet One"},
    {"name": "Split Open and Melt"},
    {"name": "The Oh Kee Pa Ceremony"},
    {"name": "Bathtub Gin"},
    {"name": "Run Like an Antelope"},
    {"name": "Lawn Boy"},
    {"name": "Bouncing Around the Room"},
    {"name": "Llama"},
    {"name": "Eliza"},
    {"name": "Cavern"},
    {"name": "Poor Heart"},
    {"name": "Stash"},
    {"name": "Manteca"},
    {"name": "Guelah Papyrus"},
    {"name": "Magilla"},
    {"name": "The Landlady"},
    {"name": "Glide"},
    {"name": "Tweezer"},
    {"name": "The Mango Song"},
    {"name": "Chalk Dust Torture"},
    {"name": "Faht"},
    {"name": "Catapult"},
    {"name": "Tweezer Reprise"},
    {"name": "Rift"},
    {"name": "Fast Enough for You"},
    {"name": "Lengthwise"},
    {"name": "Maze"},
    {"name": "Sparkle"},
    {"name": "Horn"},
    {"name": "The Wedge"},
    {"name": "My Friend, My Friend"},
    {"name": "Weigh"},
    {"name": "All Things Reconsidered"},
    {"name": "Mound"},
    {"name": "It's Ice"},
    {"name": "The Horse"},
    {"name": "Silent in the Morning"},
    {"name": "Julius"},
    {"name": "Down with Disease"},
    {"name": "If I Could"},
    {"name": "Riker's Mailbox"},
    {"name": "Axilla (Part II)"},
    {"name": "Lifeboy"},
    {"name": "Sample in a Jar"},
    {"name": "Wolfman's Brother"},
    {"name": "Scent of a Mule"},
    {"name": "Dog Faced Boy"},
    {"name": "Demand"},
    {"name": "Free"},
    {"name": "Character Zero"},
    {"name": "Waste"},
    {"name": "Taste"},
    {"name": "Cars Trucks Buses"},
    {"name": "Talk"},
    {"name": "Theme from the Bottom"},
    {"name": "Train Song"},
    {"name": "Bliss"},
    {"name": "Billy Breathes"},
    {"name": "Swept Away"},
    {"name": "Steep"},
    {"name": "Prince Caspian"},
    {"name": "Ghost"},
    {"name": "Birds of a Feather"},
    {"name": "Meat"},
    {"name": "Guyute"},
    {"name": "Fikus"},
    {"name": "Shafty"},
    {"name": "Limb By Limb"},
    {"name": "Frankie Says"},
    {"name": "Brian and Robert"},
    {"name": "Water in the Sky"},
    {"name": "Roggae"},
    {"name": "Wading in the Velvet Sea"},
    {"name": "The Moma Dance"},
    {"name": "End of Session"},
    {"name": "Farmhouse"},
    {"name": "Twist"},
    {"name": "Bug"},
    {"name": "Back on the Train"},
    {"name": "Heavy Things"},
    {"name": "Gotta Jibboo"},
    {"name": "Dirt"},
    {"name": "Piper"},
    {"name": "Sleep"},
    {"name": "The Inlaw Josie Wales"},
    {"name": "Sand"},
    {"name": "First Tube"},
    {"name": "Driver"},
    {"name": "Mountains in the Mist"},
    {"name": "Pebbles and Marbles"},
    {"name": "Anything But Me"},
    {"name": "Round Room"},
    {"name": "Mexican Cousin"},
    {"name": "Friday"},
    {"name": "Seven Below"},
    {"name": "Mock Song"},
    {"name": "46 Days"},
    {"name": "All of These Dreams"},
    {"name": "Walls of the Cave"},
    {"name": "Thunderhead"},
    {"name": "Waves"},
    {"name": "Scents and Subtle Sounds (Intro)"},
    {"name": "Undermind"},
    {"name": "The Connection"},
    {"name": "A Song I Heard the Ocean Sing"},
    {"name": "Army of One"},
    {"name": "Crowd Control"},
    {"name": "Maggie's Revenge"},
    {"name": "Nothing"},
    {"name": "Two Versions of Me"},
    {"name": "Access Me"},
    {"name": "Scents and Subtle Sounds"},
    {"name": "Tomorrow's Song"},
    {"name": "Secret Smile"},
    {"name": "Grind"},
    {"name": "Tiny"},
    {"name": "Backwards Down the Number Line"},
    {"name": "Stealing Time From the Faulty Plan"},
    {"name": "Joy"},
    {"name": "Sugar Shack"},
    {"name": "Ocelot"},
    {"name": "Kill Devil Falls"},
    {"name": "Light"},
    {"name": "I Been Around"},
    {"name": "Time Turns Elastic"},
    {"name": "Twenty Years Later"},
    {"name": "Fuego"},
    {"name": "The Line"},
    {"name": "Devotion to a Dream"},
    {"name": "Halfway to the Moon"},
    {"name": "Winterqueen"},
    {"name": "Sing Monica"},
    {"name": "555"},
    {"name": "Waiting All Night"},
    {"name": "Wombat"},
    {"name": "Wingsuit"},
    {"name": "Friends"},
    {"name": "Breath and Burning"},
    {"name": "Home"},
    {"name": "Blaze On"},
    {"name": "Tide Turns"},
    {"name": "Things People Do"},
    {"name": "Waking Up Dead"},
    {"name": "Running Out of Time"},
    {"name": "No Men In No Man's Land"},
    {"name": "Miss You"},
    {"name": "I Always Wanted It This Way"},
    {"name": "More"},
    {"name": "Petrichor"},
    {"name": "Sigma Oasis"},
    {"name": "Leaves"},
    {"name": "Everything's Right"},
    {"name": "Mercury"},
    {"name": "Shade"},
    {"name": "Evening Song"},
    {"name": "Steam"},
    {"name": "A Life Beyond The Dream"},
    {"name": "Thread"},
    {"name": "Hey Stranger"},
    {"name": "Oblivion"},
    {"name": "Evolve"},
    {"name": "A Wave of Hope"},
    {"name": "Pillow Jets"},
    {"name": "Lonely Trip"},
    {"name": "Life Saving Gun"},
    {"name": "Monsters"},
    {"name": "Ether Edge"},
    {"name": "Human Nature"},
    {"name": "Valdese"},
    {"name": "The Well"},
    {"name": "Mercy"},
]

ALBUM_SONGS = {
    "Junta": [
        "Fee",
        "You Enjoy Myself",
        "Esther",
        "Golgi Apparatus",
        "Foam",
        "Dinner and a Movie",
        "Divided Sky",
        "David Bowie",
        "Fluffhead",
        "Fluff's Travels",
        "Contact",
        "Union Federal",
        "Sanity",
        "Icculus",
    ],
    "Lawn Boy": [
        "The Squirming Coil",
        "Reba",
        "My Sweet One",
        "Split Open and Melt",
        "The Oh Kee Pa Ceremony",
        "Bathtub Gin",
        "Run Like an Antelope",
        "Lawn Boy",
        "Bouncing Around the Room",
    ],
    "A Picture of Nectar": [
        "Llama",
        "Eliza",
        "Cavern",
        "Poor Heart",
        "Stash",
        "Manteca",
        "Guelah Papyrus",
        "Magilla",
        "The Landlady",
        "Glide",
        "Tweezer",
        "The Mango Song",
        "Chalk Dust Torture",
        "Faht",
        "Catapult",
        "Tweezer Reprise",
    ],
    "Rift": [
        "Rift",
        "Fast Enough for You",
        "Lengthwise",
        "Maze",
        "Sparkle",
        "Horn",
        "The Wedge",
        "My Friend, My Friend",
        "Weigh",
        "All Things Reconsidered",
        "Mound",
        "It's Ice",
        "Lengthwise",
        "The Horse",
        "Silent in the Morning",
    ],
    "Hoist": [
        "Julius",
        "Down with Disease",
        "If I Could",
        "Riker's Mailbox",
        "Axilla (Part II)",
        "Lifeboy",
        "Sample in a Jar",
        "Wolfman's Brother",
        "Scent of a Mule",
        "Dog Faced Boy",
        "Demand",
    ],
    "Billy Breathes": [
        "Free",
        "Character Zero",
        "Waste",
        "Taste",
        "Cars Trucks Buses",
        "Talk",
        "Theme from the Bottom",
        "Train Song",
        "Bliss",
        "Billy Breathes",
        "Swept Away",
        "Steep",
        "Prince Caspian",
    ],
    "The Story of the Ghost": [
        "Ghost",
        "Birds of a Feather",
        "Meat",
        "Guyute",
        "Fikus",
        "Shafty",
        "Limb By Limb",
        "Frankie Says",
        "Brian and Robert",
        "Water in the Sky",
        "Roggae",
        "Wading in the Velvet Sea",
        "The Moma Dance",
        "End of Session",
    ],
    "Farmhouse": [
        "Farmhouse",
        "Twist",
        "Bug",
        "Back on the Train",
        "Heavy Things",
        "Gotta Jibboo",
        "Dirt",
        "Piper",
        "Sleep",
        "The Inlaw Josie Wales",
        "Sand",
        "First Tube",
        "Driver",
        "Mountains in the Mist",
    ],
    "Round Room": [
        "Pebbles and Marbles",
        "Anything But Me",
        "Round Room",
        "Mexican Cousin",
        "Friday",
        "Seven Below",
        "Mock Song",
        "46 Days",
        "All of These Dreams",
        "Walls of the Cave",
        "Thunderhead",
        "Waves",
    ],
    "Undermind": [
        "Scents and Subtle Sounds (Intro)",
        "Undermind",
        "The Connection",
        "A Song I Heard the Ocean Sing",
        "Army of One",
        "Crowd Control",
        "Maggie's Revenge",
        "Nothing",
        "Two Versions of Me",
        "Access Me",
        "Scents and Subtle Sounds",
        "Tomorrow's Song",
        "Secret Smile",
        "Grind",
        "Tiny",
    ],
    "Joy": [
        "Backwards Down the Number Line",
        "Stealing Time From the Faulty Plan",
        "Joy",
        "Sugar Shack",
        "Ocelot",
        "Kill Devil Falls",
        "Light",
        "I Been Around",
        "Time Turns Elastic",
        "Twenty Years Later",
    ],
    "Fuego": [
        "Fuego",
        "The Line",
        "Devotion to a Dream",
        "Halfway to the Moon",
        "Winterqueen",
        "Sing Monica",
        "555",
        "Waiting All Night",
        "Wombat",
        "Wingsuit",
    ],
    "Big Boat": [
        "Friends",
        "Breath and Burning",
        "Home",
        "Blaze On",
        "Tide Turns",
        "Things People Do",
        "Waking Up Dead",
        "Running Out of Time",
        "No Men In No Man's Land",
        "Miss You",
        "I Always Wanted It This Way",
        "More",
        "Petrichor",
    ],
    "Sigma Oasis": [
        "Sigma Oasis",
        "Leaves",
        "Everything's Right",
        "Mercury",
        "Shade",
        "Evening Song",
        "Steam",
        "A Life Beyond The Dream",
        "Thread",
    ],
    "Evolve": [
        "Hey Stranger",
        "Oblivion",
        "Evolve",
        "A Wave of Hope",
        "Pillow Jets",
        "Lonely Trip",
        "Life Saving Gun",
        "Monsters",
        "Ether Edge",
        "Human Nature",
        "Valdese",
        "The Well",
        "Mercy",
    ],
}
